// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopicSubscription {
    #[prost(bytes = "vec", required, tag = "1")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectPieces {
    #[prost(bytes = "vec", required, tag = "2")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub pieces_metadata: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub pieces: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
